version: "3.6"

services:
  node:
    image: node:19-alpine
    working_dir: /githubio
    command: >
      sh -c "npm install &&
      npm start"
    ports:
      - 3000:3000
    volumes:
      - ./:/githubio:Z
    tty: true
